### ISSUE TITLE
Feature - Update doc to using readthedocs

### ISSUE THREAD

**Issue by mjanez** [mjanez/ckanext-schemingdcat#103]
> [!NOTE]
> Read the Docs configuration file for MkDocs projects
> See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

## Todo
- [ ] Implements Github Actions deployment or RTD. Info: https://about.readthedocs.com/comparisons/github-pages/ and https://medium.com/medialesson/documentation-in-github-pages-with-mkdocs-readthedocs-theme-920b283215d1
- [ ] https://github.com/mjanez/ckanext-dcat/blob/master/.readthedocs.yaml
- [ ] https://github.com/mjanez/ckanext-dcat/blob/master/mkdocs.yml

**Comment by mjanez** [comment]
Adding: https://github.com/mjanez/ckanext-schemingdcat/pull/105/commits/c9f76e0b069676f5ba773fa80a88bf8b195d6cac
