### ISSUE TITLE
Feature - Improve HVD codelists to 2.1v and add applicable_legislation auto to: http://data.europa.eu/eli/reg_impl/2023/138/oj

### ISSUE THREAD

**Issue by mjanez** [mjanez/ckanext-schemingdcat#106]
- [x] Automáticamente serializar: `<http://data.europa.eu/r5r/applicableLegislation> <http://data.europa.eu/eli/reg_impl/2023/138/oj>`: `hvd_category`
- [x] Improve `hvd_category` codelist.

  > High-value dataset categories
  > Version 2.1
  > Concept scheme URI: http://data.europa.eu/bna/asd487ae75
  > Type of dataset: Taxonomy
  > https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://data.europa.eu/bna/asd487ae75
  
  ## Resources
  - https://docs.google.com/spreadsheets/d/1p4h5y82-jiH68qGY_WeCV6HuyJKmuyC1XLjVbwjsAdg/edit?gid=1340884059#gid=1340884059

### Todo
- [ ] https://github.com/mjanez/ckanext-schemingdcat/tree/main/ckanext/schemingdcat/schemas
- [ ] https://dataeuropa.gitlab.io/data-provider-manual/hvd/Reporting_guidelines_for_HVDs/

**Comment by mjanez** [comment]
Added by: https://github.com/mjanez/ckanext-schemingdcat/commit/f60645d65192d8015b929d0bdfa48b4938d27f02
